import = [
"~/alacritty-theme/theme/Cobalt2.toml"
]

[env]
TERM = "xterm-256color"

[window]
title = "allacritty"
padding.x = 10
padding.y = 30
decorations = "Buttonless"
opacity = 0.8
#blur = true
option_as_alt = "Both"

[font]
normal.family = "0xProto Nerd Font Mono"
size = 15

[cursor]
style.blinking = "On"
